version: '3.8'

services:
  webex:
    build: ./webex
    ports:
      - "8001:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
    dns:
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}

  solarwinds:
    build: ./solarwinds
    ports:
      - "8002:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
    dns:
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}

  servicenow:
    build: ./servicenow
    ports:
      - "8003:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
    dns:
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}

  dnacenter:
    build: ./dnacenter
    ports:
      - "8004:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
    dns:
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}

  sshscp:
    build: ./sshscp
    ports:
      - "8005:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
    dns:
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}

  central:
    build: ./central
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
    dns:
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}

  api-gateway:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8089"
    ports:
      - "8089:8089"
      - "8081:8089"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    dns:
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}